const categories = [
  { id: 1, name: "Motors", img: "images/drive systems.jpg" },
  { id: 2, name: "Drive Systems", img: "images/control panel.avif" },
  { id: 3, name: "Motors1", img: "images/drainage parts.jpg" },
  { id: 4, name: "Drive Systems1", img: "images/drive systems.jpg" },
  { id: 5, name: "Motors2", img: "images/drive systems.jpg" },
  { id: 6, name: "Drive Systems2", img: "images/drive systems.jpg" },
];

const products = [
  {
    id: 101,
    name: "Motor A",
    desc: "High power motor",
    img: "images/drive systems.jpg",
    price: 5000,
    brand: "Hico",
    soldOut: false,
    is_feature: false,
    category_id: 1,
  },
  {
    id: 102,
    name: "Motor B",
    desc: "Low noise motor",
    img: "images/drive systems.jpg",
    price: 7500,
    brand: "Hico",
    soldOut: true,
    is_feature: false,
    category_id: 1,
  },
  {
    id: 103,
    name: "Drive X",
    desc: "Best drive system",
    img: "images/drive systems.jpg",
    price: 12000,
    brand: "Hico",
    soldOut: false,
    is_feature: false,
    category_id: 1,
  },
  {
    id: 104,
    name: "Motor A",
    desc: "High power motor",
    img: "images/drive systems.jpg",
    price: 5000,
    brand: "Hico",
    soldOut: false,
    is_feature: true,
    category_id: 1,
  },
  {
    id: 105,
    name: "Motor A",
    desc: "High power motor",
    img: "images/drive systems.jpg",
    price: 5000,
    brand: "Hico",
    soldOut: false,
    is_feature: false,
    category_id: 1,
  },
  {
    id: 106,
    name: "Motor A",
    desc: "High power motor",
    img: "images/drive systems.jpg",
    price: 5000,
    brand: "Hico",
    soldOut: false,
    is_feature: true,
    category_id: 1,
  },

  {
    id: 201,
    name: "Drive X",
    desc: "Best drive system",
    img: "images/drive systems.jpg",
    price: 12000,
    brand: "Hico",
    soldOut: false,
    is_feature: false,
    category_id: 2,
  },

  {
    id: 301,
    name: "Motor A",
    desc: "High power motor",
    img: "images/drive systems.jpg",
    price: 5000,
    brand: "Hico",
    soldOut: false,
    is_feature: true,
    category_id: 3,
  },
  {
    id: 302,
    name: "Motor B",
    desc: "Low noise motor",
    img: "images/drive systems.jpg",
    price: 7500,
    brand: "Hico",
    soldOut: true,
    is_feature: false,
    category_id: 3,
  },

  {
    id: 401,
    name: "Drive X",
    desc: "Best drive system",
    img: "images/drive systems.jpg",
    price: 12000,
    brand: "Hico",
    soldOut: false,
    is_feature: false,
    category_id: 4,
  },

  {
    id: 501,
    name: "Motor A",
    desc: "High power motor",
    img: "images/drive systems.jpg",
    price: 5000,
    brand: "Hico",
    soldOut: false,
    is_feature: true,
    category_id: 5,
  },
  {
    id: 502,
    name: "Motor B",
    desc: "Low noise motor",
    img: "images/drive systems.jpg",
    price: 7500,
    brand: "Hico",
    soldOut: true,
    is_feature: false,
    category_id: 5,
  },

  {
    id: 601,
    name: "Drive X",
    desc: "Best drive system",
    img: "images/drive systems.jpg",
    price: 12000,
    brand: "Hico",
    soldOut: false,
    is_feature: true,
    category_id: 6,
  },
];
